// Generated by https://quicktype.io

export interface IProveedores {
    ID: string;
    NIF: string;
    Nombre: string;
    Direccion: string;
    Provincia: string;
    CP: string;
    Telefono: string;   
    cliente: IClientes
}
export interface IClientes {
    ID: string;
    DNI: string;
    Nombre: string;
    Apellido1: string;
    Apellido2: string;
    Direccion: string;
    Provincia: string;
    CP: string;
    Telefono: string;
    Fecha_nacimiento: string;
}
