// Generated by https://quicktype.io
export interface IAuth {
    ID:        string;
    Email:     string;
    Web:       string;
    isActive?: boolean;
    token?:    string;
    roles?:    string;
    FullName:  string;
    cliente:   IClientes
}

export interface IClientes{
    ID: string;
    DNI: string;
    Nombre: string;
    Apellido1: string;
    Apellido2: string;
    Direccion: string;
    Fecha_nacimiento: string;
}
