// Generated by https://quicktype.io

export interface IClientes{
    ID: string;
    DNI: string;
    Nombre: string;
    Apellido1: string;
    Apellido2: string;
    Direccion: string;
    Provincia: string;
    CP: string;
    Telefono: string;
    Fecha_nacimiento: string;
}
